name: Run processor

on:
  schedule:
  - cron:  '0 22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # cf. https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions
    #runs-on: ubuntu-22.04
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6
    
    - name: Increase git buffer size
      run: |
        git config --global http.postBuffer 1048576000
    
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v6
      with:
        python-version: 3.11.1
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt      

    - name: install gdal
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin
        sudo apt-get install libgdal-dev
    
    - name: Run Python script
      run: |
        python satromo_processor.py prod_config.py
      env: # Set the secrets as env var
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      
    - name: Push tools files to repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add --force tools/
        git diff --staged --quiet || git commit -m 'Tools files done' && git push origin main


    - name: Push processing files to repo
      run: |
        git add --force processing/
        git diff --staged --quiet || git commit -m 'Processing files done' && git push origin main
        
